### ISSUE TITLE
Enable travis-ci for automated testing

### ISSUE THREAD

**Issue by phated** [parallaxinc/PBASIC-Tokenizer#5]
@PropGit can you turn on Travis-CI for this repo?  Since we are about to land tests for the emscripten-based version, I'd like to have them running on every push to the emscripten branch.  I can't enable travis-ci without admin permissions.

**Comment by jeffam70** [comment]
I turned the repository switch on for this repo in Travis-CI.  It's settings seem to be exactly like the ChromeIDE repo.  

Is there anything else I need to do to complete this?

**Comment by phated** [comment]
@jeffam70 thanks.  Nothing more for you to do, but I will reassign to myself to get the build environment set up.  It's currently failing with g++ so I hope to dig into that at some point.

**Comment by phated** [comment]
Completed in #8
