### ISSUE TITLE
Test file encoding issues

### ISSUE THREAD

**Issue by 2fast2fourier** [parallaxinc/PBASIC-Tokenizer#7]
With the implementation of the test runner, we've exposed two test cases where extended ascii characters were not compiling as expected. I've tracked down one issue, the `tests.txt` file had been silently converted to UTF8 encoding and altered those test cases. Resolving that has fixed one of the two failing test cases from the initial test runner PR that was merged today.

The last failing test case is the same LCD example that started this. At this point, I am reasonably sure the test cases are being parsed properly from a fresh `test.txt` file. I'm looking into this further, this issue will track progress on this problem.

**Comment by jeffam70** [comment]
For ease in testing purposes, I've simplified the code that exposes this problem down to 58 characters (assuming single-character end-of-line marker).

```
'{$STAMP BS2}
'ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
OUTS = %000000000000000
```

This is _indeed_ valid code; the first two lines are a directive followed by a comment and finally executable code.

NOTE: Successively deleting a single Ä at a time from the start of the second comment line will often result in a different error message.  This behavior seems to indicate that the source being passed to the tokenizer still contains multi-byte encoding for characters above ASCII 127.

Strangely however, if you delete any four Ä characters, the code seems to compile; though I don't know if it compiled properly.

**Comment by 2fast2fourier** [comment]
I found the issue, in our `post.js`, where strings are copied into emscripten memory, we were using a writeString function that preserved unicode. Since javascript internally uses unicode encodings for the extended charset, that would copy that representation into the tokenizer. I've switched this out for the writeAscii method, which handles ascii encoding properly.

**Comment by jeffam70** [comment]
Awesome!  Thank you!

**Comment by jeffam70** [comment]
Note that there's a post in [Chrome IDE Issue 54](https://github.com/parallaxinc/ChromeIDE/issues/54) regarding translating any character that happen to be > 255 in a way that works well with the tokenizer.  See end of comment #8.

**Comment by phated** [comment]
Completed by #8
